services:
  frontend:
    image: nginx
    container_name: js-dev
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/share/nginx/html             # Mapuje lokalny kod do kontenera
      - /app/node_modules    # Chroni przed nadpisaniem modułów z kontenera przez lokalny system
    environment:
      - CHOKIDAR_USEPOLLING=true # Naprawia problemy z odświeżaniem na niektórych systemach (np. Windows/WSL)
      - WATCHPACK_POLLING=true # Pomaga w odświeżaniu na Windows/WSL
