services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: js-dev
    ports:
      - "80:80"
    volumes:
      - ./app:/app               # Mapuje lokalny kod do kontenera